version: '3'
services:

  #PHP Service
  bolao26:
    build:
      context: .
      dockerfile: Dockerfile
    image: macakosoftware/bolao26php8
    container_name: bolao26_php8
    hostname: bolao26
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: bolao26
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - app-network
    volumes:
       - ./:/var/www
       - vendor_data:/var/www/vendor
       - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:          
      - "db"

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver_php8
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ./:/var/www
      - vendor_data:/var/www/vendor
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      # MAPEAMENTO DOS CERTIFICADOS SSL:
      - ./certs:/etc/nginx/ssl/bolaocopabrothers26.online/

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db_php8
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bolao26
      MYSQL_ROOT_PASSWORD: teste123
      MYSQL_USER: bolao26
      MYSQL_PASSWORD: bolao26pass 
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    command: --init-file /data/application/init.sql
    volumes:
      - dbdata_bolao26:/var/lib/mysql
      - ./mysql/init.sql:/data/application/init.sql
    networks:
      - app-network
        
#Volumes
volumes:
  dbdata_bolao26:
    driver: local
  vendor_data:
    driver: local

#Docker Networks
networks:
  app-network:
    driver: bridge
